name: Secret Scan

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  workflow_dispatch:

jobs:
  gitleaks:
    name: Run Gitleaks Secret Scan
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Run Gitleaks
        uses: gitleaks/gitleaks-action@v2
        with:
          args: detect --redact --verbose

      # Optional: Fail the build if secrets are found
      - name: Check for leaks result
        if: failure()
        run: echo "❌ Secrets detected!" && exit 1
